#!/usr/bin/env python
import os

# https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#transfer-a-repository

repos = ['bootiful-reactive-okta', 'js-everywhere-examples', 'vaadin-flow-native',
         'weird-shutdown-on-aot-issue',
         'javabubble', 'the-clientside-aot-demo', 'declarative-clients-aot',
         'spring-boot-3-aot-graphql',
         'bootiful-flowable-2022-10-22', 'spring-integration-aot-smoke-tests',
         'joshlong-blog-migration-tool', 'spring-aot-tests-xml-constructor-args',
         'java-version-export-github-action-test',
         'lws4lyfe', 'codeone-stocks', 'cloud-native-crew-get-to-know-a-component',
         'spring-io-2022', 'declarative-clients-redux', 'fail-me-now',
         'rsocket-test-server', 'bootiful-kubernetes-operators',
         'liquibase-redux', 'batch-native-tests',
         'spring-controller', 'type-detecting-hints-for-third-party-libraries',
         'MauritianAdventure',
         'mybatis-spring-native',
         'goto-workshop-16-12-2021',
         'spring-data-native-samples',
         'jobrunr-spring-native-scratch',
         'bootiful-aot-playground', 'refreshable-vault-config-2022-08-23',
         'leveling-up-kafka', 'batch-native-hints', 'graphql-spring-native',
         'reactive-summit-keynote-2021', 'spring-authorization-server', 'rsocket-sadness-10-22-2021',
         'dual-purpose-batch-and-ws-demo ',
         'start.spring.io',
         'the-tdd-with-python-book',
         'jhipster-spring-native-ftw',
         'spring-native-jhipster-research',
         'gateway-hints',
         'spring-native',
         'global-method-security-example',
         'spring-cloud-square',
         'jetbrains-exposed-orm-native-hints',
         'ir-scratch',
         'reactive-spring-in-20m',
         'cloud-native-java-in-20m',
         'spring-boot-4tw-uni',
         'dual-purpose-batch-and-ws-demo',
         'hibernate3-maven-plugin',
         'bootiful-graalvm-native-images-with-oleg-selajev',
         'booternetes-springone-tour-may-2021-talk',
         'native-kubernetes-client-example ',
         'native-kubernetes-client ',
         'bootiful-tracing', 'bootiful-kotlin',
         'make-yourself-at-home-with-spring-native',
         'bootiful-redis-with-brian-sam-bodden',
         'bootiful-graalvm',
         'hello-clever-cloud-for-python',
         'bootiful-graalvm-webinar-03-2021',
         'bootiful-cassandra',
         'retrosocket-native',
         'bootiful-applications-2021', 'rx-websocket-graal',
         'rx-kotlin-native',
         'rsocket-and-graalvm',
         'booternetes-springone-tour-march-2021-talk',
         'redisftw',
         'bootiful-kubernetes-at-devnexus-2021',
         'booternetes-springone-tour-march-2021-workshop',
         'github-update-status-monitor',
         'you-dont-need-a-library-for-that',
         'cloud-native-java-2020',
         'bootiful-apple-m1',
         'webflux-actuator-graalvm',
         'crm-config',
         'write-docker-actions',
         'kubernetes-waiter',
         'bootiful-azure',
         'kubernetes-intro',
         'config-client-cli',
         'mistakes-were-made',
         'kuard',
         'php-seven-dot-four',
         'can-your-java-do-this',
         'ow',
         'the-spring-rest-stack',
         'simple-kotlin-boot-and-jpa-app',
         'asc-webinar-05-12-2019',
         'asc-webinar-05-12-2019-config ',
         'javascript-everywhere-api',
         'rsocket-to-me-baby',
         'rsocket-gateway-hello-world',
         'hello-s1p',
         's1p-2019-azure-spring-cloud-demo-config',
         's1p-2019-azure-spring-cloud-demo ',
         'cloudfoundry-github-action',
         'gateway-code-for-ralph',
         'spring-cloud-gateway-rsocket-sample',
         'demo-custom-initializr',
         'bootiful-kotlin-codeone-2019',
         'spring-boot-graal-feature',
         's1p-2019-better-developer-journey',
         'amigos-al-bootup',
         'reactive-mysql-with-jasync-and-r2dbc',
         'indesign-2019-scripts',
         'end-to-end-kafka-and-spring',
         'azure-service-bus-jms',
         'bootiful-redis',
         'goto-chicago-bootiful-reactive-microservices-asterclass',
         'reactive-bridge-demonstration',
         'podcast-production-pipeline-base-image',
         'http-invoker-with-spring-boot',
         'fun-with-testcontainers',
         'fun-with-blockhound',
         'podcast-production-pipeline-shell',
         'distributed-locking-with-spring-integration-locks',
         'podcast-production-pipeline-integration ',
         'kafka-producer-and-consumer ',
         'bootiful-podcast-desktop-prototype',
         'bootiful-testing-online-training',
         'bootiful-reactive-microservices',
         'r2dbc-and-rsocket-and-m4-ouch',
         'spring_io_2019',
         'photo-catalog', 'moesif-servlet', 'spring-flights',
         'spring-init-experiment',
         'inventory-hub-java-on-azure',
         'matt-and-josh-react-reactively',
         'bootiful-reactive-testing',
         'mybatis-and-spring-boot-2',
         'infoq-mini-book', 'spring-shell',
         'cloud-native-spring-part-3',
         'css-grid-design-scratch',
         'bootiful-libs',
         'geode-experiment',
         'spring-boot-maven-update',
         'relearning-python-2019',
         'reactive-couchbase-example',
         'reactive-machine-to-machine',
         'bootiful-azure-article',
         'introduction',
         'joshlong-oauth2',
         'denver-jug-with-matt-raible-13-02-2019',
         'okta.github.io',
         'kotlin-jumpstart-with-dr-subramaniam',
         'spring-boot-and-java-10',
         'ceci-nest-pas-un-bean',
         'spring-fu',
         't-t-d',
         't-t-d-content',
         'bootiful-gcp',
         'reactive-spring-online-training',
         'contrib', 'lynda-react-essentials-homework',
         'springboot-hello-azure',
         'envault',
         'bootiful-gcp-riff-function',
         'podcast-terraform-installation ',
         'goto-chicago-bootiful-reactive-microservices-masterclass ',
         'bootiful-kotlin-online-training',
         'bootiful-testing-at-s1p-2018',
         'kotlin-ready-to-ride',
         'bootiful-reactive-microservices-config',
         'asciidoctor-leanpub-converter',
         'uppercat',
         'reactive-spring-july-13-2018 ',
         'rewrite-maven-plugin',
         'reactive-websockets-java-and-spring-integration',
         'production-is-bootiful',
         'springone-tour-denver-2018-with-matt-raible',
         'spring-cloud-cli-config', 'initializr', 'movies',
         'mario-bootcamp',
         'learning-spring-boot-2nd-edition-code',
         'riff-and-spring-cloud-function',
         'spring-cloud-stream-kafka-streams',
         'bootiful-two-scratch',
         'asciidoctor-include-resolving-bridge',
         'koober', 'cloud-native-day-codecentric-2018',
         'spring-boot-admin',
         'putting-the-fun-in-spring-cloud-function',
         'spring-cloud-cloudfoundry',

         'sring-boot-cloud-elastic',
         'spring-data-neo4j-phrasebook-example',
         'spring-tips',
         'spring-boot-cloud-elastic',
         'spring-boot-dubbo',
         'spring-elasticsearch',
         'cdct-reservations',
         'service-brokers',
         'liquibase-demo',
         'dropbox-service-broker',
         'bootiful-contracts',
         'cloud-native-pwas',
         'gcp-service-broker',
         'artwork',
         'JavaEE8-Playground',
         'kafka-examples',
         'gcp-service-broker',
         'stackdriver-trace-deployer',
         'cloudfoundry-stackdriver-trace-zipkin-proxy',
         'java-buildpack',
         'stackdriver-zipkin',
         'gcp-cf-workshop',
         'spring-and-kafka',
         's3-service-broker-redux',
         'spring-cloud-pipelines-fun',
         'cloud-turtles',
         'spring-cloud-gateway',
         'couchbase-spring',
         'jooq-example',
         'sleuth-webmvc-example',
         'java-jaxrs',
         'batch-4-spring-tip',
         'cf-promoter',
         'jOOQ',
         'demo-thymeleaf',
         'github-webhook',
         'cdl3',
         'cdl4',
         'cdl1',
         'cdl2',
         'datomic-starter',
         'github-webhook',
         'spring-dist-tx',
         'retro-spring-example',
         'spring-and-google-protocol-buffers',
         'cloud-native-kotlin',
         'AxonFramework',
         'axon-boot-demo',
         'cf-task-demo',
         'blocking-sc-stream',
         's1p2017-boot-k8s',
         'greeting-cloudant-spring',
         'demo-animated-banner',
         's1p-2017-spring-tips-functional-bean-definitions',
         'bootiful-screencapture',
         'custom-spring-security-filter',
         'screencapture-gif-maker',
         'reactive-spring-article',
         'bootiful-grails',
         'kotlin-conf-2017',
         'scott-davis-static-resources-demo',
         'poormans-scs', 'prod-is-bootiful', 'kotlin-script-templating', 'hystrix-stream-webclient-reader',
         'twis-generator',
         'atomist-reactive-spring',
         'spring-cloud-sockets',
         'yow-hk-2017-workshop',
         'spring-cloud-contract-oddities',
         'summaries-with-nltk',
         'intro-to-java-tutorial',
         'rsocket-revolution',
         'bootiful-azure-spring-cloud',
         'bootiful-time-springone-2020',
         'fema-disaster-batch-job',
         'bootiful-reactive-microservices-masterclass',
         'intro-to-java-tutorial',
         'rsocket-revolution',
         'greetings-config-repository',
         'bootiful-configuration',
         'a-feign-like-rsocket-client',
         'hello-world-docker-action',
         'tanzu-tuesdays',
         'wavefront-webinar-06-2020',
         'reactive-revolution',
         'gateway-and-graalvm',
         'simple-python-github-client',
         'simple-python-github-client-test',
         'jwt-spring-boot-starter',
         'bootiful-azure-05-16-2020',
         'spring-security-sample',
         'security-jwt-fun',
         'test',
         'cloudbowl-microservice-game',
         'bootiful-graal',
         'organization-project-validation',
         'reconcile-and-dedupe',
         'ruby-emailer',
         'what-idiot-called-it-rustaceans-and-not-rustafarians',
         'github-analytics',
         'cf-spring-cloud-task-demo',
         'sagan',
         'cf-cqrs-microservice-sampler',
         'ratelimiting',
         'bucket4j',
         'authscratch',
         'top-di-with-spring',
         'spring-framework-1',
         'living-on-the-edge',
         'microservices-lab',
         'hintjens-tweets',
         'spring-boot-oauth2-demo',
         'microservices-lab',
         'top-di-with-spring',
         'spring-cloud-dataflow',
         'meh',
         'microservices-dzrc',
         'spring-boot-db-samples',
         'kcjug-data',
         'simple-cd-plugin',
         'OnlinePythonTutor',
         'cd-production-promotion',
         'cdlive-again',
         'bootiful-data',
         'cflogin',
         'these-are-the-turbine-streams-of-our-lives',
         'operationalized-applications-meetup',
         'swampup-spring-boot-demo',
         'bootiful-elasticsearch',
         'rc2woes',
         'bootiful-banners',
         'metric-source',
         'microservices-dashboard',
         'geospatial-messenger',
         'cloud-native-sso-workspace',
         'payments-demo',
         'spring-boot',
         'bootiful-data-integration-442016',
         'microservices-dashboard',
         'cloud-native-sso-workspace',
         'devoxx-poland-2015-microservices-hol',
         'sirius',
         'bootiful-docker',
         'devoxx-france-2015-microservices-hol',
         'qcon2015-sao-paolo-microservices-workshop',
         'bootiful-microservices-configuration',
         'spring-data-couchbase-talk',
         'bootiful-sessions',
         'spring-doge-microservice-configuration',
         'bootiful-webpshere',
         'spring-security-angular',
         'spring-doge-microservice',
         'service-registration-and-discovery',
         '12factor-backing-service',
         'spring-cloud-pivotal-connector',
         'nfjs_2015',
         'Activiti',
         'configuring-it-all-out',
         'boot-it-up',
         'javaone-2014',
         'bootiful-rest',
         'udp-reactor',
         'spring-security-oauth',
         'the-pivotal-microservice',
         'activiti-spring-boot-webinar',
         'vaadin-and-spring-talk',
         'activiti-spring-boot-webinar',
         'scaling-software-talk',
         'graphconnect-2014',
         'brms-coolstore-demo',
         'speakerdeck-to-slideshare',
         'bootiful-microservice-configuration',
         'bootiful-websphere',
         '12factor-backing-services',
         'iosched', 'hands-on-analysis-python',
         'accidentalDBA',
         'io-test-samples',
         'spring-microservices-workshop',
         'halfpipe',
         'sparklr-boot', 'raml-jaxrs-codegen',
         'sparklr-boot',
         'spring-framework',
         'spring-boot-gwt',
         'whats-new-in-spring-data',
         'sfdc-cloudfoundry',
         'spring-boot-embedded-tomcat-ssl',
         'vaadin4spring',
         'spring-rest-service-oauth',
         'tweet-page-chrome-extension',
         'spring-rest-service-oauth',
         'have-you-seen-spring-lately',
         'dotworkstation',
         'ibm-websphere-liberty-buildpack',
         'the-spring-data-stack',
         'adaptive-spring',
         'javaconfig-ftw',
         'spring-music',
         'spring-social-plugin',
         'pring-restbucks',
         'spring-social-flickr',
         'spring-social-glass',
         'mirror-quickstart-java',
         'cloudamqp-cf',
         'the-spring-tutorial',
         'HelloSpringJavaBasedJavaConfig',
         'spring-integration-mqtt',
         'cloudfoundry-samples',
         'spring',
         'quickstart',
         'bakehouse',
         'env-vars-sinatra',
         'github-code-proxy',
         'cf-docs',
         'spring-data-elasticsearch',
         'movie-database',
         'spring-petclinic',
         'natsaway',
         'batch-ogg-to-mp3-script',
         'akka',
         'spring-mvc-31-walkthrough',
         'spring-batch-bootcamp',
         'html5expense',
         'fha',
         'teachingv2',
         'a-walking-tour-of-spring',
         'multi-client-dev-with-spring',
         'interesting-native-code-examples',
         'spring-gemfire',
         'super-simple-Spring-application',
         'spring-data-mongodb',
         'cbeams.github.com',
         'maven-repository',
         'spring-modules',
         'mustache-spring-view',
         'the-spring-experience',
         'msgpack-rpc',
         'spring-batch-gemfire', 'integration-gateway',
         'prospringintegrationbook',
         'dac', 'joshlong-examples',
         'spring-activiti-sandbox',
         'spring-3.1-profiles-java',
         'spring-hadoop',
         'spring-batch-admin',
         'spring-integration-activiti-sandbox',
         'demo-actuator-jersey',
         'webflux-workshop',
         'custom-spring-fu-module',
         'boot-examples',
         'microservice-lab-configuration',
         'reactive-mongodb-on-cloudfoundry',
         'security-scratch',
         'agileindia-2018',
         'spring-cloud-stream-scratch',
         'reactive-integration-scratch',
         'a-sunny-day-in-frankfurt',
         'bootiful-kafka',
         'multiple-property-placeholder-configurers-in-spring-xml',
         'dynamic-columns-angular-example',
         'bootiful-angular',
         'spring-security5-oauth-client-scratch',
         'audible-notes',
         'twitter-list-maker',
         'bootiful-reactive',
         'simple-cd-example',
         'cdlive-backup',
         'atomist_example',
         'JDays2016MicroServices',
         'spring-batch',
         'sleuth-blog',
         'dataflow-shell-ac',
         'spring-reactive-playground',
         'maven-examples',
         'activiti-examples',
         'developer-advocate',
         'josh-hacks-with-kotlin-at-jfokus-speaker-event-2016',
         'spring-retry',
         'spring-cloud-stream-modules',
         'mybatis-spring-boot',
         'mybatis-boot',
         'config-repo',
         'spring-cloud-atlas-sample',
         'ci-cd-mock',
         'counterpoint-service',
         'bookmarks',
         'akka-boot-autoconfig',
         'spring-demo-rest-config',
         'type-proxy-not-present-error',
         'java-mag-boot-article',
         'blawg-content',
         'github-actions-continuous-delivery',
         'cloud-native-java-2021',
         'vue-electron-prototype',
         'spring-cloud-starters',
         'gs-centralized-configuration',
         'gs-service-registration-and-discovery',
         'spring-cloud-dataflow-starters',
         'cf-blue-green',
         'remediation',
         'power-patterns-pains-of-microservices ',
         'spring-integration-activiti',
         'vehicle-fleet-demo',
         'trace-pr',
         'the-forklifted-application',
         'bootiful-book',
         'spring-demo-rest-config',
         'the-operationalized-application',
         'sencha-spring',
         'spring-social-google',
         'activiti-neo4j',
         'markdown-to-asciidoc',
         'spring-security-oauth-javaconfig',
         'sringone2gx2013',
         'spring-social-google',
         'spring-restbucks',
         'apps-tutorial',
         'activiti-neo4j',
         'jquery-filedrop',
         'rest',
         'sixthsense',
         'cloudfoundry-in-action',
         'jso',
         'monty-hall',
         'spring-one-2012',
         'spring-birt',
         'spring-integration',
         'spring-mvc-31-demo',
         'spring-travel',
         'shopzilla-core',
         'jnats', 'nats', 'skellybones', 'maven-book',
         'podsheets',
         'multiple-datasource-spring-apps',
         'multiple-datasource-spring-apps-sample',
         'microservices-labl-configuration',
         'spring-reactive-sample',
         'simple-spring-cloud-gateway-edge-service',
         'bootiful',
         'mutliple-property-placeholder-configurers-in-spring-xml',
         'spring-projects-visualization',
         'cloudofoundry-ftp-service-broker',
         'continuous-win-with-pivotal',
         'not-a-last-minute-demo',
         'bootiful-apps-with-boot-talk',
         'spring-boot-cf-service-broker',
         'selfies',
         'bootiful-vaadin',
         'io-test-samples',
         'spring-microservice-workshop',
         'YADrone',
         'gs-accessing-facebook',
         'springone2gx2013',
         'si-extensions-testbed',
         'spring-native-infoq-article',
         'graphql-java',
         'hybrid-2-and-3-spring-boot-starters',
         'kubernetes-java-client',
         'kubernetes-waiter-github-action',
         'bootiful-applications-redux',
         ]

if __name__ == '__main__':


    def transfer(gh_pat: str, repo: str):
        '''
        this prints out the commands to migrate 
        the application from one organization to another. 
        Run this script, direct the output to a a file, say `run.sh`,
        then make that script executable (`chmod a+x run.sh`), then run it:
        `./run.sh`
        '''
        repo = repo.strip()
        cmd = '''
        curl -X POST -H "Accept: application/vnd.github+json"  -H "Authorization: Bearer %s" -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/repos/joshlong/%s/transfer  -d '{"new_owner":"joshlong-attic", "new_name":"%s"}'
        ''' % (gh_pat, repo, repo)
        return cmd.strip()


    gh_pat = os.environ['GH_PAT']
    assert gh_pat is not None, 'you must specify a github personal access token'
    cmds = [transfer(gh_pat, repo) for repo in repos]
    print(os.linesep.join(cmds))
